### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by samshipengs** [lastlegion/dc.js-server-side-crossfilter#1]
Hi, I just was trying to do npm install on ubuntu 16.04lts
but it's throwing this error that I'm not really sure what caused it even after spending time searching on internet,
```
> odbc@1.3.0 install /home/sam/dc.js-server-side-crossfilter/node_modules/odbc
> node-gyp configure build

make: Entering directory '/home/sam/dc.js-server-side-crossfilter/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
In file included from ../src/odbc.cpp:25:0:
../src/odbc.h:30:17: fatal error: sql.h: No such file or directory
compilation terminated.
odbc_bindings.target.mk:109: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory '/home/sam/dc.js-server-side-crossfilter/node_modules/odbc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-98-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/sam/dc.js-server-side-crossfilter/node_modules/odbc
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: odbc@1.3.0 (node_modules/odbc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: odbc@1.3.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 3 packages in 1.008s
```

**Comment by samshipengs** [comment]
`npm install odbc` did the trick
